package technology.rocketjump.undermount.ui.views.debug;

public enum DebugAction {

	NONE,
	SPAWN_ITEM,
	SPAWN_SETTLER,
	DESTROY_ENTITY,
	TRIGGER_FIRE,
	TRIGGER_LIGHTNING,
	TRIGGER_IMMIGRATION,
	TRIGGER_NEXT_WEATHER,
	TOGGLE_PIPE,
	TOGGLE_CHANNEL,
	UNCOVER_UNEXPLORED_AREA

}
